name: Azure Web App Deploy

on: [push]

env:
  azureapp-name: githubgoofyapp
  publish-path: './published'
  
jobs:
  build:
    name: Dotnet Build
    runs-on: ubuntu-latest
    steps:
    # setup dotnet version
      - uses: actions/checkout@main
      - name: Setup Dotnet Env
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 3.1.103
    # dotnet build & Publish
      - name: Dotnet Build & Publish
        run: dotnet publish -c Release -o ${{ env.publish-path }}
        
    # deploy to azure app
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.azureapp-name }}
          publish-profile: ${{ secrets.AZUREAPPPROFILE }}
          package: ${{ env.publish-path }}
    # download artifact in github
      - name: Download Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: webapppackage
          path: ${{ env.publish-path }}
          
