name: Azure App Deploy

on: [push]

env:
  azure-app-name: goofyapp400
  app-package-path: './published'
  dotnet-version: 3.1.103

jobs:
  build:
    name: Azure App Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.103
      - name: Restore & Build-Publish
        run: dotnet publish -c Release -o ./published
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with: 
          app-name: ${{env.azure-app-name }}
          publish-profile: ${{ secrets.AZUREAPPPROFILE }}
          package: ${{ env.app-package-path }}
        
        
      

